### ISSUE TITLE
Cannot override or disable default plugins (remark-math, remark-gfm) via props

### ISSUE THREAD

**Issue by bebeal** [vercel/streamdown#162]
### Bug Description

User-provided `rehypePlugins` and `remarkPlugins` props are appended to the default plugins instead of allowing prop overrides. This prevents disabling built-in plugins like `remark-math` without resorting to build-time module aliasing hacks.

### Steps to Reproduce

1. Try to disable math parsing by passing an empty `remarkPlugins` prop 
2. Observe that `remark-math` still processes math syntax because defaults are hardcoded first

### Expected Behavior

Props should take precedence over defaults, allowing removal or replacement of default plugins.

### Actual Behavior

Props are spread after the defaults making it impossible to disable or override built-in plugins: https://github.com/vercel/streamdown/blob/main/packages/streamdown/index.tsx#L137-L146

```jsx
remarkPlugins={[
  [remarkGfm, remarkGfmOptions],
  [remarkMath, remarkMathOptions],
  ...(remarkPlugins ?? []),  // Props appended after defaults
]}
```

### Code Sample

Currently requires aliasing the entire `remark-math` module to a no-op function to disable math parsing:

```tsx
// vite.config.ts
resolve: {
  alias: {
    'remark-math': path.resolve(__dirname, 'src/lib/noop-remark-math.ts'),
  },
}
```

```tsx
// src/lib/noop-remark-math.ts
export default () => {
  /* empty */
};
```

### Streamdown Version

1.0.12

### React Version

19.1.1

### Node.js Version

20

### Browser(s)

Chrome

### Operating System

macOS

**Comment by haydenbleasel** [comment]
Done! Added `remarkMathOptions` and `remarkGfmOptions`, will be available in the next release 🙏

**Comment by bebeal** [comment]
Thanks for the quick response, but I think there may be a misunderstanding about the issue.

Adding `remarkMathOptions` and `remarkGfmOptions` allows configuring the plugins, but doesn't solve the core problem: there's no way to disable or replace the default plugins entirely.

The issue is that `remarkPlugins` props are appended after the defaults, not used instead of them. This means:
- I cannot remove `remark-math` if I don't want math parsing at all
- I cannot replace it with a different plugin implementation
- The plugins are always included regardless of what I pass in props

The fix would be to make the prop override the defaults:
```jsx
remarkPlugins={[
  ...(remarkPlugins ?? [
    [remarkGfm, remarkGfmOptions],
    [remarkMath, remarkMathOptions],
  ]),
]}
```

**Comment by haydenbleasel** [comment]
Hey @bebeal I'm familiar with the overarching issue, I'm handling that in another issue related to composition, bundle sizes, etc. Enhancement for that will be up in the next release also 😂

**Comment by bebeal** [comment]
🔥 TY!
