### ISSUE TITLE
For some reason Streamdown started to spam logs.

### ISSUE THREAD

**Issue by uriafranko** [vercel/streamdown#211]
### Bug Description

I don't really know how to reproduce it, it just started happened on my project I'm using Streamdown v1.4.0

<img width="1346" height="445" alt="Image" src="https://github.com/user-attachments/assets/dd3565b1-0fd9-4365-a0b8-ec5d001a730b" />

### Steps to Reproduce

I don't really know how to reproduce it, it just started happened on my project I'm using Streamdown v1.4.0

### Expected Behavior

Not spamming logs

### Actual Behavior

For each word the agent returns it produces few 1000s of debug logs that crash the system

### Code Sample

```tsx
Just ai-sdk (ai elements) both ways
```

### Streamdown Version

1.4.0

### React Version

19

### Browser(s)

Chrome

### Operating System

None

**Comment by sudoskys** [comment]
Perhaps you accidentally set debug mode.
Try checking localStorage; that might help.

**Comment by jkracz** [comment]
I also have this issue. It only happens when running dev, not in my deployed env. But it easily gets up hundreds of thousands of logs. I'm assuming there is some dev/debug mode getting set somewhere but I'm not seeing it set anywhere in localStorage like you mentioned @sudoskys .
Looking at the docs, I also don't see a way to manually configure debug/dev mode.

Streamdown Version
1.5.1

React Version
19.2 (Vite with Tanstack start)

Node.js Version
22

Browser(s)
Chrome

**Comment by sudoskys** [comment]
@jkracz Here
https://github.com/orgs/micromark/discussions/209
https://github.com/orgs/micromark/discussions/102
https://github.com/micromark/micromark?tab=readme-ov-file#size--debug

**Comment by songkeys** [comment]
i have the exact issue. configuring `debug` does not work.  https://github.com/orgs/micromark/discussions/209#discussioncomment-14994805

i believe it's a bundling bug from vite + tanstack start. It seems that you're using the same stack.

**Comment by songkeys** [comment]
Update: this should be fixed in this release: https://github.com/vercel/streamdown/releases/tag/streamdown%401.6.3 where it now has browser builds. @haydenbleasel thanks for the work!

**Comment by haydenbleasel** [comment]
Awesome, I was just about to look into this @songkeys - thanks for the heads up!

**Comment by jkracz** [comment]
Thanks for following up on this everyone! I recently upgraded to 1.6.7, but am still seeing tons of logs (whether I set the debug flag or not). I've run clean installs, cleared my cache, but nothing seems to be getting rid of these logs. Maybe I'm missing something?

**Comment by jkracz** [comment]
@haydenbleasel following up, I determined the issue was actually with the Nitro version we were running. I upgraded from "3.0.1-alpha.0" to "3.0.1-alpha.1" and the streamdown logs went away immediately.

**Comment by haydenbleasel** [comment]
Nice find @jkracz ! I was digging to find the reason, maybe they were Nitro logs that _appeared_ to be coming from Streamdown? Not sure but glad its resolved 👀

**Comment by jkracz** [comment]
@haydenbleasel I think you're right. I just tested it with streamdown completely uninstalled and the logs are still hitting.
Glad this is fixed. thanks for your support!
