### ISSUE TITLE
Extra Dollar Signs in Latex block With `\begin`

### ISSUE THREAD

**Issue by freymend** [vercel/streamdown#54]
### Bug Description

When streamdown renders latex that contains a `\begin` command with `parseIncompleteMarkdown = true`, the first instance of the `\begin` will be improperly closed with `$$`. 

### Steps to Reproduce

1. Set `parseIncompleteMarkdown` to `true`
2. Render latex that contains `\being{}`
3. Observe `$$` in the output

### Expected Behavior

Image of expected behavior

<img width="381" height="128" alt="Image" src="https://github.com/user-attachments/assets/6c3faf95-cb70-4744-bd92-ba5bf200a6c1" />

### Actual Behavior

Image of actual behavior

<img width="317" height="51" alt="Image" src="https://github.com/user-attachments/assets/b089d495-855d-45f1-b623-dbeecd322a6e" />

### Code Sample

```tsx
import { Streamdown } from 'streamdown';

function App() {
  const test_issue = `
  $$
  \\begin{pmatrix}
  x \\\\
  y
  \\end{pmatrix}
  =
  $$
`;

  return (
    <div style={{ marginLeft: 10 }}>
      <h1>Extra dollar signs</h1>
      <Streamdown>{test_issue}</Streamdown>
      <h1>No extra dollar signs</h1>
      <Streamdown parseIncompleteMarkdown={false}>{test_issue}</Streamdown>
    </div>
  );
}

export default App;
```

### Streamdown Version

1.1.4

### React Version

18.3.1

### Node.js Version

22

### Browser(s)

Chrome

### Operating System

macOS

**Comment by haydenbleasel** [comment]
@freymend this may have been fixed as of #64 - I'm not seeing the issue on my side but are you able to verify for me with the latest Streamdown?

**Comment by freymend** [comment]
<img width="417" height="198" alt="Image" src="https://github.com/user-attachments/assets/ec8547ec-7191-4646-bb2d-3b030def47d9" />

Streamdown 1.1.6 still shows the issue for me. If I remove the `=` it renders correctly.

**Comment by haydenbleasel** [comment]
okay thanks for checking, i'll keep digging 🙏

**Comment by freymend** [comment]
@haydenbleasel sorry for the ping, but I can't seem to open new bug reports.

**Comment by haydenbleasel** [comment]
@freymend issue reporting is fixed - was a broken github template 👍
